# System Dependencies
SET(
  SYSTEM_LIBRARIES
  Winmm
)

# Generate libraries from system library list
FOREACH(LIBRARY ${SYSTEM_LIBRARIES})
  ADD_LIBRARY("System::${LIBRARY}" INTERFACE IMPORTED GLOBAL)
  SET_PROPERTY(
    TARGET "System::${LIBRARY}"
    PROPERTY IMPORTED_LIBNAME "${LIBRARY}"
  )
ENDFOREACH()

IF(NOT TARGET Microsoft::CppWinRT)
  # VCPKG Dependencies
  SET(DEP_PACKAGES
    Microsoft.GSL
    fmt
    spdlog
    yaml-cpp
    cppwinrt
    magic_enum
    nlohmann_json)

  FOREACH(depPkgName ${DEP_PACKAGES})
    FIND_PACKAGE(${depPkgName} CONFIG REQUIRED)
  ENDFOREACH()

  FIND_PACKAGE(ICU REQUIRED COMPONENTS uc i18n data)
ENDIF()

# Create Similar Aliases for each Dependency
SET(DEP_ICU ICU::uc ICU::i18n ICU::data)
SET(DEP_YAML yaml-cpp::yaml-cpp)
SET(DEP_JSON nlohmann_json::nlohmann_json)
SET(DEP_MAGICENUM magic_enum::magic_enum)
SET(DEP_GSL Microsoft.GSL::GSL)
SET(DEP_LOG spdlog::spdlog)
SET(DEP_SYS_WINMM System::Winmm)
SET(DEP_FMT fmt::fmt)
SET(DEP_LOG spdlog::spdlog ${DEP_FMT})

SET(ALL_APP_DEPS
  ${DEP_JSON}
  ${DEP_MAGICENUM}
  ${DEP_FMT}
  ${DEP_LOG}
  ${DEP_YAML}
  ${DEP_GSL}
  ${DEP_SYS_WINMM}
  ${DEP_ICU}
)

SET(ALL_SDK_DEPS
  ${DEP_MAGICENUM}
  ${DEP_GSL}
  ${DEP_FMT}
  ${DEP_YAML}
  ${DEP_LOG}
  ${DEP_SYS_WINMM}
  ${DEP_ICU}
)

FUNCTION(IRSDKCPP_TARGET_LINK_SDK_LIBS TARGET)
  TARGET_LINK_LIBRARIES(${TARGET} PUBLIC ${ALL_SDK_DEPS})
ENDFUNCTION()

FUNCTION(IRSDK_CPP_CONFIGURE_APP_LIBS TARGET)
  TARGET_LINK_LIBRARIES(${TARGET} PRIVATE ${ALL_APP_DEPS})
ENDFUNCTION()

IF(IRSDKCPP_BUILD_TESTS)
  FIND_PACKAGE(GTest CONFIG REQUIRED)
  SET(DEP_GTEST_MAIN GTest::gtest GTest::gtest_main GTest::gmock)
  SET(DEP_GTEST GTest::gtest GTest::gmock)

  FUNCTION(IRSDK_CPP_CONFIGURE_TESTS_EXE TARGET)
    TARGET_LINK_LIBRARIES(${TARGET} ${ALL_APP_DEPS} ${DEP_GTEST_MAIN})
  ENDFUNCTION()
ENDIF()
