INCLUDE(GenerateExportHeader)
INCLUDE(GNUInstallDirs)
INCLUDE(CMakeParseArguments)

MACRO(SETUP_TARGET_COMPILE_DEFS targetName)
  TARGET_COMPILE_DEFINITIONS(
    ${targetName}
    PRIVATE
    $<$<CONFIG:Debug>:DEBUG>
    BUILD_TYPE="${CMAKE_BUILD_TYPE}"
    FMT_USE_STRING_VIEW
    SPDLOG_NO_EXCEPTIONS=1
    SPDLOG_WCHAR_SUPPORT=1
    SPDLOG_WCHAR_TO_UTF8_SUPPORT=1
  )
ENDMACRO()

FUNCTION(IRSDK_CPP_CONFIGURE_TARGET_RUNTIME_STATIC TARGET)
  SET_PROPERTY(TARGET ${TARGET} PROPERTY
    MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>")
ENDFUNCTION()

FUNCTION(IRSDK_CPP_CONFIGURE_TARGET_RUNTIME_DYNAMIC TARGET)
  SET_PROPERTY(TARGET ${TARGET} PROPERTY
    MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>DLL")
ENDFUNCTION()

FUNCTION(IRSDK_CPP_CONFIGURE_TARGET TARGET)
  SETUP_TARGET_COMPILE_DEFS(${TARGET})

ENDFUNCTION()